config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :manufacturers do
    resources :cars
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer
  validates :color, presence: true
  validates :year, presence: true, numericality: { greater_than_or_equal_to: 1920 }
  validates :mileage, presence: true
  validates :manufacturer, presence: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  validates :name, presence: true
  validates :country, presence: true

  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ActionController::Base
  def create
    @car = Car.new(car_params)
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @car.manufacturer = @manufacturer

    if @car.save
      flash[:notice] = "You successfully created a car."
      redirect_to manufacturer_path(@manufacturer)
    else
      flash[:notice] = "Your record could not be saved."
      render 'manufacturers/show'
    end
  end

  private

  def car_params
    params.require(:car).permit(:color, :mileage, :year)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ActionController::Base
  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      flash[:notice] = "You successfully created a manufacturer."
      redirect_to root_path
    else
      flash[:notice] = "Your record could not be saved."
      render 'new'
    end
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
    @car = Car.new
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country, :id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  def index
    @manufacturers = Manufacturer.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/manufacturers/new.html.erb
<%= form_for @manufacturer do |f| %>
  <% if @manufacturer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@manufacturer.errors.count, "error") %> prohibited
            this review from being saved:</h2>
          <ul>
            <% @manufacturer.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end%>
    <p>
      <%= f.label :name  %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :country  %><br>
      <%= f.text_field :country %>
    </p>

    <%= f.submit "Create Manufacturer" %>
<% end %>

app/views/manufacturers/show.html.erb
<%= flash[:notice] %><br>



<h1>List of Cars Made by <%= @manufacturer.name %></h1>
<h4>Country: <%= @manufacturer.country %></h4>
<ol>
  <% @manufacturer.cars.each do |car| %>
    <li> <%= car.color %> -- <%= car.year %> -- <%= car.mileage %></li>
  <% end %>
</ol>
<%= form_for [@manufacturer, @car] do |f| %>
<% if @car.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@car.errors.count, "error") %> prohibited
          this review from being saved:</h2>
        <ul>
          <% @car.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end%>
  <p>
    <%= f.label :color  %><br>
    <%= f.text_field :color %>
  </p>
  <p>
    <%= f.label :year  %><br>
    <%= f.text_field :year %>
  </p>
  <p>
    <%= f.label :mileage  %><br>
    <%= f.text_field :mileage %>
  </p>
  <p>
    <%= f.label :description  %><br>
    <%= f.text_field :description %>
  </p>

  <%= f.submit "Create Car" %>
<% end %>
<br>
<%= link_to "Home", root_path %>

app/views/welcome/index.html.erb
<%= flash[:notice] %><br>
<%= link_to "Submit New Manufacturer", new_manufacturer_path %><br>


<h1> List of Manufacturers</h1>
<ul>
  <% @manufacturers.each do |manufacturer| %>
    <li><%= link_to manufacturer.name, manufacturer_path(manufacturer) %></li>
  <% end %>
</ul>